name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./fe
        run: |
          npm ci
          npm run build

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_SERVER_IP: ${{ vars.SSH_SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          # Sync frontend build
          rsync -avz --delete ./fe/dist/ root@${{ vars.SSH_SERVER_IP }}:/opt/nextgen/fe/dist/
          
          # Sync backend
          rsync -avz --delete --exclude 'node_modules' --exclude '.env' ./be/ root@${{ vars.SSH_SERVER_IP }}:/opt//nextgen/be/

      - name: Install Backend Dependencies & Restart Services
        run: |
          ssh root@${{ vars.SSH_SERVER_IP }} << 'EOF'
            cd /opt/nextgen/be
            npm ci --production
            pm2 restart sun
            systemctl restart nginx
          EOF

      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/id_rsa
